version: '3'
services:
  book-app:
    build: .
    ports:
      - '8080:8080'
      - '5005:5005'
    depends_on:
      - mysql
    environment:
      - DEBUG=true
  mysql:
    image: mysql:8
    container_name: mysql
    hostname: mysql
    ports:
      - '6603:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
